name: backend-build

on:
  push:
    branches: [ develop ]
    paths:
      - 'pom.xml'
      - 'src/**'
      - '.github/workflows/build.yml'
  # Trigger anche quando crei un tag tipo v1.0.0
  create:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build (skip tests per velocità)
        run: mvn -B -DskipTests package