name: CI - Build & Test (Develop)

on:
  push:
    branches: [ "develop" ]
    paths:
      - "pom.xml"
      - "src/**"
      - ".github/workflows/ci-build.yml"
  pull_request:
    branches: [ "develop" ]
    paths:
      - "pom.xml"
      - "src/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "maven"

      - name: Build & Test
        run: ./mvnw -B -ntp test package